# Generated by Django 4.2.13 on 2024-06-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("professor_name", models.CharField(max_length=100)),
                (
                    "question_1",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
                (
                    "question_2",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
                (
                    "question_3",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
                (
                    "question_4",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
                (
                    "question_5",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
                (
                    "question_6",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
                (
                    "question_7",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
                (
                    "question_8",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
                (
                    "question_9",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
                (
                    "question_10",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
                (
                    "question_11",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
                (
                    "question_12",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
                (
                    "question_13",
                    models.CharField(
                        choices=[("SIM", "SIM"), ("NÃO", "NÃO")], max_length=3
                    ),
                ),
            ],
        ),
    ]
